version: '3.8'
services:
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  api:
    build: ./apps/api
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/studyarchive
      - NODE_ENV=production
    restart: unless-stopped
  web:
    build: ./apps/web
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:4000/api/v1
    restart: unless-stopped
volumes:
  mongo-data:
